### ISSUE TITLE
TODO: Employ collection_select

### ISSUE THREAD

**Issue by bodrovis** [Femchengdu/horse_hotel#3]
This is https://github.com/Femchengdu/horse_hotel/blob/cf6d3c47a2c655b772ee3c25b94bf9df7e22b247/app/views/bookings/_form.html.erb#L18 way too complicated (especially the underlying method)

There is a great helper that generates dropdowns for collections: http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-collection_select

It also can be used like this: http://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-collection_select

After we setup the proper associations for all the models, the form can be re-written!

**Comment by bodrovis** [comment]
Also, no need to make it a symbol: https://github.com/Femchengdu/horse_hotel/blob/cf6d3c47a2c655b772ee3c25b94bf9df7e22b247/app/views/bookings/_form.html.erb#L17

Actually, I'd recommend sticking with I18n instead, but let's put it aside for now. I'll show you later how it can be done.

**Comment by Femchengdu** [comment]
Thanks for the feedback,

I have deleted the day model and sent a pull request for you to review.
If you approve above the pull request, can I delete the branch after it has
been merged?

 Once approved, I would create another branch to tackle the issues you have
raised.


Warm regards,
Femi Ajayi

**Comment by bodrovis** [comment]
@Femchengdu Of course. Once the branch is merged, the code is in master. So, the branch can be removed!
