### ISSUE TITLE
Has many through for bookings and stalls

### ISSUE THREAD

**Issue by bodrovis** [Femchengdu/horse_hotel#6]
So, as discussed earlier, a stall can be booked multiple times. What we can do is introduce a `User` (or `Client`) model and establish has many through relation. `Booking` will acts as an intermediate table then:

```ruby
# user.rb
has_many :bookings
has_many :stalls, through: :bookings
```

```ruby
# booking.rb
belongs_to :user
belongs_to :stall
```

```ruby
# stall.rb
has_many :bookings
has_many :users, through: :bookings
```

Booking will contain date fields representing duration.

Let's discuss this, as you may have other thoughts.

**Comment by Femchengdu** [comment]
I have one question about the User model, would it also serve the Stable owners?

**Comment by bodrovis** [comment]
@Femchengdu Brilliant question. Yes, I think it will, why not. I mean, we CAN differentiate clients and owners for some reason. I don't know, for example, to treat them differently later. If you do not forsee such requirement, then let's make `User` an owner as well. We can even call the relation like this:

```ruby
# horse_stable.rb
belongs_to :owner, class_name: 'User', foreign_key: 'user_id' # if your column is named `user_id`, it must be stated explicitly
```

```ruby
# user.rb
has_many :horse_stalls
```

Something like that.
